services:
  jarswaf-controller:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jarswaf_controller
    command: ["/app/jarswaf", "controller"]
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/var/log/jarswaf
