apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarswaf.fullname" . }}-secrets
  labels:
    {{- include "jarswaf.labels" . | nindent 4 }}
type: Opaque
data:
  gossip-psk: {{ .Values.secrets.gossip.psk | b64enc | quote }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.secrets.redis.password | b64enc | quote }}
  {{- end }}
