use serde::Deserialize;
use std::collections::HashMap;
use std::fs::File;
use std::io::{BufRead, BufReader, Write};

#[derive(Deserialize, Debug)]
struct ComplianceEvent {
    #[serde(rename = "@timestamp")]
    timestamp: String,
    event: EventMeta,
    source: SourceMeta,
    rule: RuleMeta,
    compliance_tags: Vec<String>,
}

#[derive(Deserialize, Debug)]
struct EventMeta {
    action: String,
}

#[derive(Deserialize, Debug)]
struct SourceMeta {
    ip: String,
}

#[derive(Deserialize, Debug)]
struct RuleMeta {
    id: String,
}

pub fn generate_report(log_path: &str, output_path: &str) {
    println!("Generating compliance report from: {}", log_path);
    let file = match File::open(log_path) {
        Ok(f) => f,
        Err(e) => {
            println!("Failed to open ECS log file '{}': {}", log_path, e);
            println!("Make sure JARSWAF has processed some traffic to generate ECS logs.");
            return;
        }
    };

    let reader = BufReader::new(file);

    let mut total_events = 0;
    let mut blocked_events = 0;
    let mut compliance_counts: HashMap<String, usize> = HashMap::new();
    let mut top_ips: HashMap<String, usize> = HashMap::new();

    for line in reader.lines() {
        if let Ok(line_content) = line {
            if line_content.trim().is_empty() {
                continue;
            }
            if let Ok(event) = serde_json::from_str::<ComplianceEvent>(&line_content) {
                total_events += 1;
                if event.event.action == "blocked" {
                    blocked_events += 1;
                }

                *top_ips.entry(event.source.ip).or_insert(0) += 1;

                for tag in event.compliance_tags {
                    *compliance_counts.entry(tag).or_insert(0) += 1;
                }
            }
        }
    }

    let mut report = String::new();
    report.push_str("# JARSWAF PCI-DSS Compliance Report\n\n");
    report.push_str(&format!(
        "**Generated At:** {}\n\n",
        chrono::Utc::now().to_rfc3339()
    ));

    report.push_str("## 1. Executive Summary\n");
    report.push_str(&format!("- **Total Analyzed Events:** {}\n", total_events));
    report.push_str(&format!("- **Blocked Threats:** {}\n", blocked_events));
    let allowed = total_events - blocked_events;
    report.push_str(&format!("- **Allowed Traffic:** {}\n\n", allowed));

    report.push_str("## 2. Compliance Requirements Mapping\n");
    report.push_str("| Requirement Tag | Event Count | Description |\n");
    report.push_str("|---|---|---|\n");
    for (tag, count) in &compliance_counts {
        let desc = match tag.as_str() {
            "PCI-DSS-Req-10" => "Logging & Monitoring of Access",
            "PCI-DSS-Req-6" => "Secure Systems against SQLi/XSS",
            "PCI-DSS-Req-4" => "Protect Data in Transit (API/JWT)",
            _ => "Unknown Requirement",
        };
        report.push_str(&format!("| `{}` | {} | {} |\n", tag, count, desc));
    }
    report.push_str("\n");

    report.push_str("## 3. Top Source IPs\n");
    let mut sorted_ips: Vec<_> = top_ips.into_iter().collect();
    sorted_ips.sort_by(|a, b| b.1.cmp(&a.1));
    for (ip, count) in sorted_ips.iter().take(5) {
        report.push_str(&format!("- `{}`: {} events\n", ip, count));
    }

    report.push_str("\n---\n*Report auto-generated by JARSWAF Security Module (Gen-4)*\n");

    match File::create(output_path) {
        Ok(mut f) => {
            if let Err(e) = f.write_all(report.as_bytes()) {
                println!("Failed to write report: {}", e);
            } else {
                println!(
                    "✅ Compliance report generated successfully at: {}",
                    output_path
                );
            }
        }
        Err(e) => println!("Failed to create output file: {}", e),
    }
}
